spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_deni
    username: prod_user
    password: deni123
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true